id = "ollama"
category = "dev"
subcategory = "ia"
dependencies = []

[install]
cmd = "curl -fsSL https://ollama.com/download/ollama-linux-amd64.tar.zst -o /tmp/ollama.tar.zst && tar -xzf /tmp/ollama.tar.zst -C /usr && rm -f /tmp/ollama.tar.zst"
